// 스캔 결과 → 에이전트가 읽는 지도(마크다운) 생성
// 왜 마크다운인가: 코딩 에이전트는 저장소의 텍스트 파일을 그대로 읽는다.
// 별도 서버·플러그인 없이 파일만 놓아두면 어떤 에이전트(Claude Code·Cursor·Copilot)든 쓴다.

const bar = (n, max, width = 24) => '█'.repeat(Math.max(1, Math.round((n / max) * width)))

export function renderAtlas({ repoName, files, modules, ambiguities, symbolIndex }) {
  const totalLines = files.reduce((s, f) => s + f.lines, 0)
  const maxFiles = Math.max(...modules.map((m) => m.files), 1)
  const high = ambiguities.filter((a) => a.severity === 'high')
  const medium = ambiguities.filter((a) => a.severity === 'medium')

  const lines = []
  lines.push(`# ${repoName} — Codebase Atlas`)
  lines.push('')
  lines.push('> Map for AI coding agents. Read this before searching or editing.')
  lines.push('> Generated by agent-compass. Regenerate after structural changes.')
  lines.push('')
  lines.push('## Scale')
  lines.push('')
  lines.push(`- Files indexed: **${files.length.toLocaleString()}**`)
  lines.push(`- Lines: **${totalLines.toLocaleString()}**`)
  lines.push(`- Modules: **${modules.length}**`)
  lines.push(`- Ambiguous filenames: **${high.length + medium.length}** (high risk: ${high.length})`)
  lines.push('')
  lines.push('## Modules')
  lines.push('')
  lines.push('| module | files | lines | |')
  lines.push('|---|---:|---:|---|')
  for (const m of modules.slice(0, 40)) {
    lines.push(`| \`${m.name}\` | ${m.files} | ${m.lines.toLocaleString()} | ${bar(m.files, maxFiles)} |`)
  }
  lines.push('')

  if (high.length || medium.length) {
    lines.push('## ⚠️ Ambiguous filenames — read this before editing')
    lines.push('')
    lines.push('The same filename exists in more than one place. An agent told to')
    lines.push('"fix X" can edit the wrong copy and appear to change nothing.')
    lines.push('Always confirm the module prefix before opening one of these.')
    lines.push('')
    for (const a of [...high, ...medium].slice(0, 40)) {
      const flag = a.severity === 'high' ? '🔴' : '🟡'
      lines.push(`### ${flag} \`${a.name}\` — ${a.count} copies${a.similar ? ' (near-identical sizes)' : ''}`)
      for (const f of a.files.slice(0, 12)) lines.push(`- \`${f.path}\` (${f.lines} lines)`)
      lines.push('')
    }
  }

  lines.push('## Symbol index')
  lines.push('')
  lines.push('Exported names → file. Duplicated names are marked; those are the')
  lines.push('ones an agent most often resolves to the wrong file.')
  lines.push('')
  const dupSymbols = [...symbolIndex.entries()].filter(([, v]) => v.length > 1)
  const uniqSymbols = [...symbolIndex.entries()].filter(([, v]) => v.length === 1)
  lines.push(`- unique symbols: ${uniqSymbols.length.toLocaleString()}`)
  lines.push(`- duplicated symbols: **${dupSymbols.length.toLocaleString()}**`)
  lines.push('')
  if (dupSymbols.length) {
    lines.push('| symbol | defined in |')
    lines.push('|---|---|')
    for (const [name, paths] of dupSymbols.slice(0, 60)) {
      lines.push(`| \`${name}\` | ${paths.slice(0, 6).map((p) => `\`${p}\``).join('<br>')} |`)
    }
    lines.push('')
  }
  lines.push('---')
  lines.push('')
  lines.push('Rule of thumb: **when this map and the code disagree, the code is right.**')
  lines.push('Regenerate the map instead of trusting a stale one.')
  return lines.join('\n')
}

export function renderModulePage(mod, symbolsByFile) {
  const lines = []
  lines.push(`# ${mod.name}`)
  lines.push('')
  lines.push(`Files: ${mod.files} · Lines: ${mod.lines.toLocaleString()}`)
  lines.push('')
  lines.push('| file | lines | exports |')
  lines.push('|---|---:|---|')
  const sorted = [...mod.paths].sort((a, b) => b.lines - a.lines).slice(0, 400)
  for (const f of sorted) {
    const syms = (symbolsByFile.get(f.path) || []).slice(0, 8)
    lines.push(`| \`${f.path}\` | ${f.lines} | ${syms.map((s) => `\`${s}\``).join(' ') || '—'} |`)
  }
  return lines.join('\n')
}

export function renderReport({ files, modules, ambiguities, symbolIndex }) {
  const high = ambiguities.filter((a) => a.severity === 'high')
  const medium = ambiguities.filter((a) => a.severity === 'medium')
  const dupSymbols = [...symbolIndex.entries()].filter(([, v]) => v.length > 1)
  return {
    files: files.length,
    lines: files.reduce((s, f) => s + f.lines, 0),
    modules: modules.length,
    ambiguousHigh: high.length,
    ambiguousMedium: medium.length,
    duplicatedSymbols: dupSymbols.length,
    worst: high.slice(0, 5).map((a) => ({ name: a.name, count: a.count })),
  }
}
